services:
  astra_api:
    build:
      context: ./astra_api
      # target: dev
    restart: unless-stopped
    ports:
      - "5245:80"
    volumes:
      - ./astra_api:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80

  astra_ui:
    container_name: astra_ui
    build:
      context: ./astra_ui
      target: dev
    ports:
      - "4000:5173"
    volumes:
      - ./astra_ui:/app
      - /app/node_modules
  
  # Ephemerides API Service
  sideris:
    container_name: sideris
    build:
      context: ./sideris
      # target: dev
    restart: unless-stopped
    ports:
      - "8624:8624"
    volumes:
      - ./sideris:/app

    command: uvicorn sideris:app --reload --host 0.0.0.0 --port 8624
